# Generated by Django 4.1.4 on 2023-01-02 07:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stack", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="user_reaction",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="react", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.FileField(
                default="uploads/image.jpg", null=True, upload_to="uploads/%Y/%m/%d"
            ),
        ),
    ]
