# Generated by Django 4.1.4 on 2023-01-02 08:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stack", "0002_question_user_reaction_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="user_reaction",
            field=models.ManyToManyField(
                related_name="react", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
