# Generated by Django 4.1.4 on 2023-01-01 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stack", "0003_alter_answer_downvote_alter_answer_upvote_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={"ordering": ["-upvote", "-created_at"]},
        ),
    ]
